### ISSUE TITLE
Incorrect link in release notes.

### ISSUE THREAD

**Issue by GPXCoder** [erkle64/FoundryCommands#2]
The link, taken from the release notes and revealed below is pointing to the older version file.

v1.6.0 [Latest](https://github.com/erkle64/FoundryCommands/releases/latest)
@erkle64 [erkle64](https://github.com/erkle64) released this Jan 22
[ v1.6.0](https://github.com/erkle64/FoundryCommands/tree/v1.6.0)
https://github.com/erkle64/FoundryCommands/commit/cc54f73868cc58afed17990a5e8355fa908e9f1c
Installation
Extract FoundryCommands_x64.zip
https://  github[.]com/erkle64/FoundryCommands/releases/download/**v1.5.2**/FoundryCommands_x64.zip
to the Foundry root folder and say yes to overwriting file.

**Comment by erkle64** [comment]
Thank you.  Corrected it.
