### ISSUE TITLE
/drag mode

### ISSUE THREAD

**Issue by AliensHive** [erkle64/FoundryCommands#4]
/drag doesn't seem to work. Blue grid isn't getting bigger than 38x38. Tried in SinglePlayer and Multiplayer with "/drag 100"

**Comment by AliensHive** [comment]
FoundryCommands only works in SinglePlayer. Installed on Dedicated Server crashed the server.

**Comment by erkle64** [comment]
Thanks.  I've restored and fixed the /drag command in v1.6.2 and I've included a fix for dedicated servers.
Let me know if it has fixed the crash for you.

**Comment by AliensHive** [comment]
> Thanks. I've restored and fixed the /drag command in v1.6.2 and I've included a fix for dedicated servers. Let me know if it has fixed the crash for you.

Nope, still not working in Multiplayer (not tested on dedicated), but /drag ignores completely all values (e.g. /drag 100). 
I used it in combination with BulkDemolishTerrain in the past.

Additionally, /give always gives a desync to all connected players.

**Comment by AliensHive** [comment]
WORKS!
Even on dedicated server no desyncs anymore. Thanks!
