### ISSUE TITLE
Feature suggestion: Set time of day

### ISSUE THREAD

**Issue by deasmi** [erkle64/FoundryCommands#5]
As I sit here waiting for the sun to come up and start charging my batteries it occurred to me I'd love to be able to set the time of day.

**Comment by erkle64** [comment]
I'll see if I can add it.  In the mean time you can press shift+alt+O to enable the debug panel and then press O to toggle it.  There's a button in there to advance time by 1 hour each click.

**Comment by erkle64** [comment]
Added in [v1.6.4](https://github.com/erkle64/FoundryCommands/releases/tag/v1.6.4).
