### ISSUE TITLE
Item names with parenthese

### ISSUE THREAD

**Issue by cemntcat** [erkle64/FoundryCommands#7]
How does one properly handle item names with parentheses?  for example "/give Transformer (Large)"  does not actually spawn the large transformer.

/give Transformer Large -- "No matching item template"
/give Transformer II -- "No matching item template"

**Comment by erkle64** [comment]
It was a miswritten regex.  I've fixed it in [v1.6.6](https://github.com/erkle64/FoundryCommands/releases/tag/v1.6.6).
It should work as expected now.  Even "/give Transformer (L" should be enough for it to work.
